Spring 2015/C#/On-Call Assistant Project/On-Call Assistant/On-Call Assistant/Models/OnCallRotation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace On_Call_Assistant.Models
{
    /* NOTE TO SELF: UPON RESCAFFOLDING OnCallRotation, USE PARTIAL CLASSES!!!
     * Also, copy modified views before rescaffolding.
     */
    public class OnCallRotation
    {
        [Key]
        [Column("ID")]
        public int rotationID { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Start Date")]
        public DateTime startDate { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "End Date")]
        public DateTime endDate { get; set; }

        [Display(Name = "Primary On-Call")]
        public bool isPrimary { get; set; }

        [ForeignKey("employee")]
        [Display(Name = "Employee")]
        public int employeeID { get; set; }

        public virtual Employee employee { get; set; }
        public virtual ICollection<PaidHoliday> holidays { get; set; }
    }
}

Spring 2015/C#/On-Call Assistant Project/On-Call Assistant/On-Call Assistant/Controllers/OnCallRotationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using On_Call_Assistant.DAL;
using On_Call_Assistant.Models;

namespace On_Call_Assistant.Controllers
{
    public partial class OnCallRotationsController : Controller
    {
        private OnCallContext db = new OnCallContext();

        // GET: OnCallRotations
        /*public async Task<ActionResult> Index()
        {
            var onCallRotations = db.onCallRotations.Include(o => o.employee);
            return View(await onCallRotations.ToListAsync());
        }*/

        // GET: OnCallRotations/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OnCallRotation onCallRotation = await db.onCallRotations.FindAsync(id);
            if (onCallRotation == null)
            {
                return HttpNotFound();
            }
            return View(onCallRotation);
        }

        // GET: OnCallRotations/Create
        public ActionResult Create()
        {
            ViewBag.employeeID = new SelectList(db.employees.OrderBy(x => x.lastName), "ID", "employeeName");
            return View();
        }

        // POST: OnCallRotations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "rotationID,startDate,endDate,isPrimary,employeeID")] OnCallRotation onCallRotation)
        {
            if (ModelState.IsValid)
            {
                db.onCallRotations.Add(onCallRotation);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.employeeID = new SelectList(db.employees.OrderBy(x => x.lastName), "ID", "employeeName", onCallRotation.employeeID);
            return View(onCallRotation);
        }

        // GET: OnCallRotations/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OnCallRotation onCallRotation = await db.onCallRotations.FindAsync(id);
            if (onCallRotation == null)
            {
                return HttpNotFound();
            }
            ViewBag.employeeID = new SelectList(db.employees.OrderBy(x => x.lastName), "ID", "employeeName", onCallRotation.employeeID);
            return View(onCallRotation);
        }

        // POST: OnCallRotations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "rotationID,startDate,endDate,isPrimary,employeeID")] OnCallRotation onCallRotation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(onCallRotation).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.employeeID = new SelectList(db.employees.OrderBy(x => x.lastName), "ID", "employeeName", onCallRotation.employeeID);
            return View(onCallRotation);
        }

        // GET: OnCallRotations/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OnCallRotation onCallRotation = await db.onCallRotations.FindAsync(id);
            if (onCallRotation == null)
            {
                return HttpNotFound();
            }
            return View(onCallRotation);
        }

        // POST: OnCallRotations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            OnCallRotation onCallRotation = await db.onCallRotations.FindAsync(id);
            db.onCallRotations.Remove(onCallRotation);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Spring 2015/C#/On-Call Assistant Project/On-Call Assistant/On-Call Assistant/Views/OnCallRotations/Create.cshtml
@model On_Call_Assistant.Models.OnCallRotation

@{
    ViewBag.Title = "Create";
}
@section styles {
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
}

@section scripts {
    <script src="~/Scripts/bootstrap.min.js"></script>
}


<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OnCallRotation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.startDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.JQueryUI().DatepickerFor(model => model.startDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.startDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.endDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">@Html.JQueryUI().DatepickerFor(model => model.endDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.endDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isPrimary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.isPrimary, new { @checked = "checked" })
                    @Html.ValidationMessageFor(model => model.isPrimary, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.employeeID, "Employee", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("employeeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.employeeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Spring 2015/C#/On-Call Assistant Project/On-Call Assistant/On-Call Assistant/Views/OnCallRotations/Delete.cshtml
@model On_Call_Assistant.Models.OnCallRotation

@{
    ViewBag.Title = "Delete";
}
@section styles {
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
}

@section scripts {
    <script src="~/Scripts/bootstrap.min.js"></script>
}


<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OnCallRotation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.employee.employeeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.employee.employeeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.startDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.startDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.endDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.endDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isPrimary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isPrimary)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Spring 2015/C#/On-Call Assistant Project/On-Call Assistant/On-Call Assistant/Views/OnCallRotations/Details.cshtml
@model On_Call_Assistant.Models.OnCallRotation

@{
    ViewBag.Title = "Details";
}
@section styles {
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
}

@section scripts {
    <script src="~/Scripts/bootstrap.min.js"></script>
}


<h2>Details</h2>

<div>
    <h4>OnCallRotation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.employee.employeeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.employee.employeeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.startDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.startDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.endDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.endDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isPrimary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isPrimary)
        </dd>

    </dl>
</div>
<p>
    <a class="btn btn-primary btn-sm" href="/home">
    Back to Calendar</a>&nbsp;&nbsp;
    @Html.ActionLink("Edit", "Edit", new { id = Model.rotationID }) |
    @Html.ActionLink("List View", "Index")
</p>

Spring 2015/C#/On-Call Assistant Project/On-Call Assistant/On-Call Assistant/Views/OnCallRotations/Edit.cshtml
@model On_Call_Assistant.Models.OnCallRotation

@{
    ViewBag.Title = "Edit";
}
@section styles {
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
}

@section scripts {
    <script src="~/Scripts/bootstrap.min.js"></script>
}


<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OnCallRotation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.rotationID)

        <div class="form-group">
            @Html.LabelFor(model => model.startDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.JQueryUI().DatepickerFor(model => model.startDate, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.startDate, "", new { @class = "text-danger", style = "width: 1000px;" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.endDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.JQueryUI().DatepickerFor(model => model.endDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.endDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isPrimary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isPrimary)
                    @Html.ValidationMessageFor(model => model.isPrimary, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.employeeID, "Employee", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("employeeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.employeeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Spring 2015/C#/On-Call Assistant Project/On-Call Assistant/On-Call Assistant/Views/OnCallRotations/GenerateSchedule.cshtml
@model IEnumerable<On_Call_Assistant.Models.OnCallRotation>

@{
    ViewBag.Title = "Generated Schedule";
    ViewBag.AppName = "On-Call Assistant";
}


@section styles {
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
}

@section scripts {
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script>
    var url = "/oncallrotations/regenerateSchedule?begin="
    $('#ReGenerateSchedule').click(function (event) {
        event.preventDefault();
        var start = document.getElementById('datepickerS').value;
        var end = document.getElementById('datepickerE').value;
        window.location.replace(url.concat(start,"&end=",end));
        });

    $(function() {
        $( "#datepickerS" ).datepicker();
    });
    $(function () {
        $("#datepickerE").datepicker();
    });

    </script>
}

<h2>@ViewBag.Title</h2>
<p>Start Date : <input type="text" id="datepickerS"></p><p>End Date : <input type="text" id="datepickerE"></p>
<p>
    <button id="ReGenerateSchedule" class="btn btn-primary btn-lg" type="button" onclick='this.disabled = "disabled";'>Regenerate Schedule</button>
    <a href="/OnCallRotations/DownloadSchedule"
       style="margin-bottom:15px">Download</a>
</p><br />


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.startDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.endDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.isPrimary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.employee.employeeName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.startDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.endDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.isPrimary)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.employee.employeeName)
        </td>
    </tr>
}

</table>

Spring 2015/C#/On-Call Assistant Project/On-Call Assistant/On-Call Assistant/Views/OnCallRotations/Index.cshtml
@model PagedList.IPagedList<On_Call_Assistant.Models.OnCallRotation>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Rotaions List";
    ViewBag.AppName = "On-Call Assistant";
}
@section styles {
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
}

@section scripts {
    <script src="~/Scripts/bootstrap.min.js"></script>
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>




        <div class="row" style="margin-bottom:15px">
            <div class="col-md-6">
@using (Html.BeginForm("Index", "OnCallRotations", FormMethod.Get))
{
    <div>
        Find Employee @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input class="btn btn-primary btn-sm" type="submit" value="Search" />
    </div>

}
    </div>
<div class="col-md-6" align="right">
    <!--page number-->
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
</div>
    </div>




<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Start Date", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            End Date
        </th>
        <th>
            Primary On-Call
        </th>
        <th>
            @Html.ActionLink("Employee", "Index", new { sortOrder = ViewBag.EmpSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            <span class="glyphicon glyphicon-edit"></span>
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.startDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.endDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.isPrimary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.employee.employeeName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.rotationID }) |
                @Html.ActionLink("Details", "Details", new { id = item.rotationID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.rotationID })
            </td>
        </tr>
    }

</table>
<div align="center">
    <!--page navigation-->
    @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
</div>
<br />